### ISSUE TITLE
Migrate command gives "TypeError: attribute name must be string, not 'bytes'"

### ISSUE THREAD

**Issue by akgandlur** [djng/djng#10]
On installing the updated version of the app, I'm getting this error.
![screen shot 2015-04-24 at 2 18 56 am](https://cloud.githubusercontent.com/assets/6627060/7307171/633725a6-ea28-11e4-8d65-d25c2bd2f976.png)

Thanks in advance.

**Comment by aeby** [comment]
Thanks for reporting. It was a python 3 problem as I generated the migrations under python 2.7. You can remove the 'b' prefix from the 'objects' string in [server/accounts/migrations/0001_initial.py](https://github.com/djng/djng/blob/master/server/accounts/migrations/0001_initial.py#L37). 
What else did you have to do to get this project running on python 3.4?

**Comment by aeby** [comment]
I reported this django bug here: https://code.djangoproject.com/ticket/24701

**Comment by akgandlur** [comment]
Thanks a lot! 
I had issues with wsgiref on Python 3.4. I had to workaround using mod_wsgi.
