### ISSUE TITLE
Celery Support

### ISSUE THREAD

**Issue by jmorrice** [djng/djng#13]
I'm struggling to add a celery worker to the Procfile with this file structure. The '--pythonpath core' parameter isn't supported by celery. Has anyone found a solution to this?

**Comment by aeby** [comment]
Did you try to set the `--workdir`?

    celery worker --workdir=server --app=core

**Comment by aeby** [comment]
Did this solve your problem?

**Comment by jmorrice** [comment]
Yes worked fine, thanks a lot!
